### PR TITLE
Fixed "blocked cookies" delete button position

### PR DESCRIPTION
**Pull request by jansensan**
- Fixed "blocked cookies" delete button position.
- Standardized code indentation and other minor linting inconsistencies.

### CODE REVIEW

**Comment by jansensan** [comment]
@fcapano The linting corrections make the changes a bit more complex to view than they really are. The correction for the position of the bucket are on lines 60-83 of options_pages/block_rules.js.

**Comment by jansensan** [comment]
@fcapano Have you been able to take a look at this PR?

**Comment by fcapano** [comment]
Hi @jansensan, sorry for the late answer!
I've had a run at the PR, but it looks like the change from position fixed to relative breaks the layout of the "+ block cookie" button, and it gets shifted down.
screenshot_2016-12-17_12-07-33
I'll have a better look to understand what's happening there

**Comment by jansensan** [comment]
Ah, I hadn't noticed that. I'll take a look when I have a moment as well.

**Comment by jansensan** [comment]
@fcapano I updated my PR so that the layout is not borked anymore.

**Comment by fcapano** [comment]
Thanks!

**Pull request merged**
